// Code generated by MockGen. DO NOT EDIT.
// Source: techwave/repository (interfaces: DepartmentRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_department_repository.go -package=mocks techwave/repository DepartmentRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "techwave/models"

	gomock "go.uber.org/mock/gomock"
)

// MockDepartmentRepositoryInterface is a mock of DepartmentRepositoryInterface interface.
type MockDepartmentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockDepartmentRepositoryInterfaceMockRecorder is the mock recorder for MockDepartmentRepositoryInterface.
type MockDepartmentRepositoryInterfaceMockRecorder struct {
	mock *MockDepartmentRepositoryInterface
}

// NewMockDepartmentRepositoryInterface creates a new mock instance.
func NewMockDepartmentRepositoryInterface(ctrl *gomock.Controller) *MockDepartmentRepositoryInterface {
	mock := &MockDepartmentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepositoryInterface) EXPECT() *MockDepartmentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartmentRepositoryInterface) Create(department models.Department) (models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", department)
	ret0, _ := ret[0].(models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentRepositoryInterfaceMockRecorder) Create(department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentRepositoryInterface)(nil).Create), department)
}

// Delete mocks base method.
func (m *MockDepartmentRepositoryInterface) Delete(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentRepositoryInterface)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockDepartmentRepositoryInterface) Get(id int) (models.Department, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(models.Department)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDepartmentRepositoryInterfaceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDepartmentRepositoryInterface)(nil).Get), id)
}

// GetByCode mocks base method.
func (m *MockDepartmentRepositoryInterface) GetByCode(code string) (models.Department, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", code)
	ret0, _ := ret[0].(models.Department)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockDepartmentRepositoryInterfaceMockRecorder) GetByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockDepartmentRepositoryInterface)(nil).GetByCode), code)
}

// List mocks base method.
func (m *MockDepartmentRepositoryInterface) List() []models.Department {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]models.Department)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockDepartmentRepositoryInterfaceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDepartmentRepositoryInterface)(nil).List))
}

// Update mocks base method.
func (m *MockDepartmentRepositoryInterface) Update(id int, updates models.Department) (models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates)
	ret0, _ := ret[0].(models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentRepositoryInterfaceMockRecorder) Update(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentRepositoryInterface)(nil).Update), id, updates)
}
