// Code generated by MockGen. DO NOT EDIT.
// Source: techwave/repository (interfaces: EnrollmentRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_enrollment_repository.go -package=mocks techwave/repository EnrollmentRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "techwave/models"
	repository "techwave/repository"

	gomock "go.uber.org/mock/gomock"
)

// MockEnrollmentRepositoryInterface is a mock of EnrollmentRepositoryInterface interface.
type MockEnrollmentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockEnrollmentRepositoryInterfaceMockRecorder is the mock recorder for MockEnrollmentRepositoryInterface.
type MockEnrollmentRepositoryInterfaceMockRecorder struct {
	mock *MockEnrollmentRepositoryInterface
}

// NewMockEnrollmentRepositoryInterface creates a new mock instance.
func NewMockEnrollmentRepositoryInterface(ctrl *gomock.Controller) *MockEnrollmentRepositoryInterface {
	mock := &MockEnrollmentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockEnrollmentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentRepositoryInterface) EXPECT() *MockEnrollmentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEnrollmentRepositoryInterface) Create(enrollment models.Enrollment) (models.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", enrollment)
	ret0, _ := ret[0].(models.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) Create(enrollment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).Create), enrollment)
}

// Delete mocks base method.
func (m *MockEnrollmentRepositoryInterface) Delete(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockEnrollmentRepositoryInterface) Get(id int) (models.Enrollment, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(models.Enrollment)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).Get), id)
}

// GetByCourseID mocks base method.
func (m *MockEnrollmentRepositoryInterface) GetByCourseID(courseID int) []models.Enrollment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCourseID", courseID)
	ret0, _ := ret[0].([]models.Enrollment)
	return ret0
}

// GetByCourseID indicates an expected call of GetByCourseID.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) GetByCourseID(courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCourseID", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).GetByCourseID), courseID)
}

// GetByStudentAndCourse mocks base method.
func (m *MockEnrollmentRepositoryInterface) GetByStudentAndCourse(studentID, courseID int) (models.Enrollment, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStudentAndCourse", studentID, courseID)
	ret0, _ := ret[0].(models.Enrollment)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByStudentAndCourse indicates an expected call of GetByStudentAndCourse.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) GetByStudentAndCourse(studentID, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStudentAndCourse", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).GetByStudentAndCourse), studentID, courseID)
}

// GetByStudentID mocks base method.
func (m *MockEnrollmentRepositoryInterface) GetByStudentID(studentID int) []models.Enrollment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStudentID", studentID)
	ret0, _ := ret[0].([]models.Enrollment)
	return ret0
}

// GetByStudentID indicates an expected call of GetByStudentID.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) GetByStudentID(studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStudentID", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).GetByStudentID), studentID)
}

// GetEnrollmentStats mocks base method.
func (m *MockEnrollmentRepositoryInterface) GetEnrollmentStats() repository.EnrollmentStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrollmentStats")
	ret0, _ := ret[0].(repository.EnrollmentStats)
	return ret0
}

// GetEnrollmentStats indicates an expected call of GetEnrollmentStats.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) GetEnrollmentStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrollmentStats", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).GetEnrollmentStats))
}

// List mocks base method.
func (m *MockEnrollmentRepositoryInterface) List() []models.Enrollment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]models.Enrollment)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).List))
}

// Update mocks base method.
func (m *MockEnrollmentRepositoryInterface) Update(id int, updates models.Enrollment) (models.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates)
	ret0, _ := ret[0].(models.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEnrollmentRepositoryInterfaceMockRecorder) Update(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEnrollmentRepositoryInterface)(nil).Update), id, updates)
}
